"""Repository boundary for the DFS platform catalog."""

from __future__ import annotations

from typing import Protocol

from dfs.domain.catalog import FilterOption, PlatformDetail, PlatformFilter, PlatformProfile, PlatformSummary


class PlatformRepository(Protocol):
    def search(self, filters: PlatformFilter) -> list[PlatformSummary]: ...

    def count(self, filters: PlatformFilter) -> int: ...

    def get_by_id(self, ship_id: int) -> PlatformDetail | None: ...

    def get_profile_by_id(self, profile_id: int) -> PlatformProfile | None: ...

    def list_factions(self) -> list[FilterOption]: ...

    def list_fleets(self, faction_id: int | None = None) -> list[FilterOption]: ...

    def list_priorities(self) -> list[FilterOption]: ...

    def list_traits(self) -> list[FilterOption]: ...

    def list_weapons(self) -> list[FilterOption]: ...
